[package]
name = "damn-fine-toot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.25.0"
toml = "0.7.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mastodon-async]
version = "1.1.0"
features = ["toml", "mt"]

